### ISSUE TITLE
Possible to use this with the HomeAssistant RTL add-on?

### ISSUE THREAD

**Issue by Kebo2r** [swoboda1337/acurite-esphome#6]
I'm a newb at this stuff but have RTL433 working with the usb dongle and HA add-on accurate to MQTT.  I like what youre doing here with making the Rain sensors etc show usable data.  Is it possible to integrate this with that setup?  Thanks!

**Comment by swoboda1337** [comment]
My stuff works with esphome on an esp32. Would just be easier to buy one of these boards: https://www.aliexpress.com/item/4000396836096.html

You dont need a dongle or MQTT, just plug that in somewhere and it will talk to HA directly over WiFi.

**Comment by swoboda1337** [comment]
![Screenshot_2024-05-20-13-38-18-06_c3a231c25ed346e59462e84656a70e50](https://github.com/swoboda1337/acurite-esphome/assets/154711427/c90e19fb-5e09-4d28-aae8-4b03fad7a612)

Can click on any of those and see graphs etc

**Comment by swoboda1337** [comment]
![image](https://github.com/swoboda1337/acurite-esphome/assets/154711427/0e302959-d1d4-45b5-9bf9-7bfbd850e741)

This is my weather stuff atm. Each of those has graphs too. I do plan on adding support for wind sensors too.

**Comment by Kebo2r** [comment]
That looks great!  My issue is the rainfall amount I’m receiving is some cumulative amount.  Not sure how to interpret that into what you’re showing as I don’t really understand where it’s coming from.  Sent from my iPhoneOn May 20, 2024, at 12:43, Jonathan Swoboda ***@***.***> wrote:﻿
image.png (view on web)
This is my weather stuff atm. Each of those has graphs too. I do plan on adding support for wind sensors too.

**Comment by swoboda1337** [comment]
I have one number coming from my esp32 and that is the cumulative amount. In HA in configuration.yaml:

```
sensor:
  - platform: statistics
    name: "Backyard Rainfall 15Min"
    entity_id: sensor.backyard_rainfall
    state_characteristic: change
    max_age:
      minutes: 15
  - platform: statistics
    name: "Backyard Rainfall 1Hr"
    entity_id: sensor.backyard_rainfall
    state_characteristic: change
    max_age:
      hours: 1
  - platform: statistics
    name: "Backyard Rainfall 24Hr"
    entity_id: sensor.backyard_rainfall
    state_characteristic: change
    max_age:
      days: 1
  - platform: statistics
    name: "Backyard Rainfall 48Hr"
    entity_id: sensor.backyard_rainfall
    state_characteristic: change
    max_age:
      days: 2
```

and 

```
utility_meter:
  daily_rainfall:
    source: sensor.backyard_rainfall
    name: "Backyard Rainfall Daily"
    always_available: true
    periodically_resetting: false
    cron: "0 0 * * *"
  weekly_rainfall:
    source: sensor.backyard_rainfall
    name: "Backyard Rainfall Weekly"
    always_available: true
    periodically_resetting: false
    cron: "0 0 * * SUN"
  monthly_rainfall:
    source: sensor.backyard_rainfall
    name: "Backyard Rainfall Monthly"
    always_available: true
    periodically_resetting: false
    cron: "0 0 1 * *"
```

I also has a binary sensor to detect if it is raining atm, that is added in settings->devices->helpers:

`{{states('sensor.backyard_rainfall_15min')|float > 0}}`

It is important that the base sensor (in this case sensor.backyard_rainfall) has force_update set to true or some of these will return unknown as the database only gets update when things change and if nothing changes there will not be anything in the database to compare against.
